spring.application.name=MyFin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/myfin
spring.datasource.username=riadh
spring.datasource.password=riadh
